//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguageConverter.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABSENCE REASONS.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit__AbsenceReasons {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit__AbsenceReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The absence reason to be deleted.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit__AbsenceReasonToBeDeleted {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit__AbsenceReasonToBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABSENCE TYPES.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit__AbsenceTypes {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit__AbsenceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit__Error {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit__Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason can not be deleted because it is designated to replace another reason..
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit__ReasonCannotBeDeleted {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit__ReasonCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence reason(s) to be deleted.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_AbsenceReasonToBeDeleted {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_AbsenceReasonToBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The absence reason has been used in the reported absences, to delete the reason, please replace it by selecting another reason below..
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_BtnAbsenceReasonReported {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_BtnAbsenceReasonReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new reason.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_BtnAddNewReason {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_BtnAddNewReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_BtnCancel {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_BtnClose {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTINUE.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_BtnContinue {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_BtnOK {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_BtnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_Confirm {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-day consecutive days:.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_DivFullDayConsecutiveDays {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_DivFullDayConsecutiveDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the convenience of guardians listening to the list of choices on the phone system, we recommend that no more than 9 absences reasons are used..
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_DivGuardiansRecommendation {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_DivGuardiansRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. consecutive days allowed:.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_DivMaxConsecutiveDaysAllowed {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_DivMaxConsecutiveDaysAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. cumulative days allowed:.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_DivMaxCumulativeDaysAllowed {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_DivMaxCumulativeDaysAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reason for replacement..
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_DivNoReasonForReplacement {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_DivNoReasonForReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the deleting reason with the following..
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_DivReplaceDeletingReason {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_DivReplaceDeletingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_H4Mapping {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_H4Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_H4Warning {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_H4Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason &lt;span id=&quot;exDelReason&quot;&gt;&lt;/span&gt; can not be deleted because it is designated to replace another reason..
        /// </summary>
        public static string Dist_AbsenceOptionSetting2__AbsenceOptionEdit_ReasonCannotBeDeleted {
            get {
                return ResourceManager.GetString("Dist_AbsenceOptionSetting2__AbsenceOptionEdit_ReasonCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Format Requirements: CSV file with date (yyyy/mm/dd), event type (must be one of: Holiday, Exam Day and In-Session), description..
        /// </summary>
        public static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
    }
}
